### ISSUE TITLE
REQUEST: University type

### ISSUE THREAD

**Issue by stephengade** [kaf-lamed-beyt/ng-universities#15]
As a user, I want to browser to:

- [ ] be able to browse all federal universities only
- [ ] be able to browse all state universities only
- [ ] be able to browse all private universities only

I think adding a key-value pair `type: 'federal'` etc., will solve that.

**Comment by kaf-lamed-beyt** [comment]
Sure thing. You can add a property in the JSON schema and also create a `UniversityType` in `api/universities` 

Ideally, you should make it a union type.

**Comment by stephengade** [comment]
Okay
