### ISSUE TITLE
[ENHANCEMENT]: Logo format

### ISSUE THREAD

**Issue by stephengade** [kaf-lamed-beyt/ng-universities#23]
Logos should have an extension `.png, .jpg, .webp` etc., for ease of use 

e.g for NOUN `https://nou.edu.ng/wp-content/uploads/2021/12/Logo-1.png` instead of a generic logo pointing to a web page
e.g for UI `https://cdn.brandfetch.io/idXOPEdb_t/w/400/h/400/theme/dark/icon.jpeg?c=1bfwsmEH20zzEfSNTed`

The current logos don't do anything unless the users of the API want to download the logos before they use them which doesn't make sense. 

I tried getting normal logo URLs for most schools that can be used easily but there are none even on the school websites, they have big variants of their logos

I saw a repo consisting of all Nigerian universities' logos [here](https://github.com/joshuaalex/Nigerian_Tertiary_Institutions_and_Logos), is there a way we can use them?

**Comment by kaf-lamed-beyt** [comment]
Thank you for spotting this. 

We may not be able to go through the process of downloading the zip file in the repo you shared and now figure out a way to host them elsewhere. 

Instead, let's leverage MySchoolPortal. If you're up to it, kindly update the README with an instruction asking contributors to click on the university name they want to add, so it'll take them to a page like this: 

![image](https://github.com/user-attachments/assets/7b6a3b0e-9208-45e3-869a-e28ffc2c2e0a)

Then, they can right-click on the image and copy the image address. 

While you're on this too, It'd be wonderful if you can help update the logo URLs that are invalid currently in the JSON files.

**Comment by stephengade** [comment]
Okay.

I am going to send a PR when this morning. Was quite busy today

**Comment by kaf-lamed-beyt** [comment]
Ayy! No problem, chief!
